# Site
repository: xu-zhang-1987/xu-zhang-1987.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Xu Zhang
title: Applied Scientist 
email: xzhnamz@amazon.com 
website: https://xu-zhang-1987.github.io/

# Social links
github_username: spongezhang
linkedin_username: xu-zhang-22008054
googlescholar_username: efE70pEAAAAJ

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I'm an applied scientist in Amazon Alexa AI. I was a postdoctoral research scientist at Digital Video and MultiMedia Lab at the Columbia University in the city of New York, supervised by Prof. Shih-Fu Chang. I obtained a Ph.D. from Tsinghua University, Beijing, China, in 2016, supervised by Prof. Shengjin Wang. My research interests include local feature detection and description, large scale image retrieval and image forensics. Here is my full [resume](doc/Xu_Zhang_resume.pdf).
  
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I'm a big fan of scuba diving, photography and volleyball.  

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
